// 직접 작성한 파일럿 초안입니다. 사전 예문이나 음성 파일을 복제하지 않았습니다.
const rows = [
[0,'ready','/ˈrɛdi/','형용사','준비가 된','prepared · 준비를 마쳤다는 점을 더 강조해요.','unprepared · 준비되지 않은','일상','I’m ready to …','Are you ready to go?','갈 준비 됐어요?','Your order is ready.','주문하신 것이 준비됐어요.','I’m ready for my Pilates class.','필라테스 수업을 들을 준비가 됐어요.'],
[0,'need','/niːd/','동사','필요하다','require · 같은 뜻으로 더 격식 있게 써요.',null,'일상','I need …','I need a little help.','도움이 조금 필요해요.','Do you need a receipt?','영수증이 필요하세요?','We need more space for the mats.','매트를 놓을 공간이 더 필요해요.'],
[0,'help','/hɛlp/','동사','돕다','assist · 더 격식 있는 말이에요.',null,'일상','Could you help me …?','I can help you with that.','제가 그 일을 도와드릴 수 있어요.','Could you help me find this address?','이 주소를 찾는 걸 도와주시겠어요?','This picture helps me explain the movement.','이 그림이 동작을 설명하는 데 도움이 돼요.'],
[0,'wait','/weɪt/','동사','기다리다','stay · 머무른다는 뜻으로, 기다림이 꼭 포함되지는 않아요.',null,'미국 생활','I can wait until …','I’ll wait outside.','밖에서 기다릴게요.','Could you wait a minute?','잠깐 기다려 주시겠어요?','Please wait until the class ends.','수업이 끝날 때까지 기다려 주세요.'],
[0,'bring','/brɪŋ/','동사','가져오다','carry · 옮기거나 들고 있다는 점을 강조해요.','take · 다른 곳으로 가져가다. 이동 방향이 달라요.','일상','I’ll bring …','I’ll bring some water.','물을 좀 가져올게요.','Can you bring your ID?','신분증을 가져오실 수 있나요?','Please bring a mat to class.','수업에 매트를 가져와 주세요.'],
[0,'choose','/tʃuːz/','동사','고르다','select · 더 격식 있게 선택을 나타내요.',null,'일상','I’d like to choose …','You can choose any color.','어떤 색이든 고르셔도 돼요.','Which one would you choose?','어느 것을 고르시겠어요?','Let’s choose a lighter shade.','조금 더 밝은 색조를 골라 봐요.'],
[0,'open','/ˈoʊpən/','형용사','영업 중인','operating · 운영 중이라는 더 넓은 뜻이에요.','closed · 영업이 끝난','미국 생활','Is … open today?','The store is open.','가게가 영업 중이에요.','Are you open on Sundays?','일요일에도 영업하시나요?','The studio is open until six.','스튜디오는 여섯 시까지 운영해요.'],
[0,'early','/ˈɝːli/','부사','이른 시간에','ahead of time · 정해진 시간보다 미리라는 뜻이에요.','late · 늦게','일상','I’ll arrive early for …','I woke up early today.','오늘은 일찍 일어났어요.','Could we meet a little early?','조금 일찍 만날 수 있을까요?','Please arrive early for your first class.','첫 수업에는 일찍 도착해 주세요.'],
[0,'breathe','/briːð/','동사','숨을 쉬다','inhale · 숨을 들이마시는 동작만 가리켜요.',null,'몸과 움직임','I breathe slowly when …','Breathe slowly for a moment.','잠시 천천히 숨을 쉬어 보세요.','Can you breathe through your nose?','코로 숨을 쉬실 수 있나요?','Keep breathing as you move.','움직이면서 계속 숨을 쉬세요.'],
[0,'bend','/bɛnd/','동사','구부리다','flex · 관절이나 근육을 굽히는 맥락에 써요.','straighten · 곧게 펴다','몸과 움직임','I bend my …','Bend your knees a little.','무릎을 조금 구부려 보세요.','Can you bend your elbow?','팔꿈치를 구부리실 수 있나요?','Bend your legs slowly.','다리를 천천히 구부리세요.'],
[0,'color','/ˈkʌlər/','명사','색','hue · 색상 자체를 가리키는 조금 더 전문적인 말이에요.',null,'디자인','My favorite color is …','I like this color.','이 색이 마음에 들어요.','Does this come in another color?','이 제품은 다른 색도 있나요?','This color makes the room feel warm.','이 색 덕분에 방이 따뜻하게 느껴져요.'],
[0,'save','/seɪv/','동사','파일이나 내용을 저장하다','store · 보관한다는 뜻으로 더 넓게 써요.','delete · 저장한 내용을 삭제하다','디지털 생활','I’ll save …','I saved the photo on my phone.','사진을 휴대폰에 저장했어요.','How do I save this file?','이 파일은 어떻게 저장하나요?','Please save your design before you close the app.','앱을 닫기 전에 디자인을 저장해 주세요.'],
[1,'adjust','/əˈdʒʌst/','동사','상황에 맞게 조금 조정하다','modify · 일부를 바꾸다. 작은 조절만 뜻하지는 않아요.',null,'몸과 움직임','I need to adjust …','I need to adjust my schedule.','일정을 좀 조정해야 해요.','Could you adjust the seat for me?','좌석을 좀 조절해 주시겠어요?','Let’s adjust the colors in this design.','이 디자인의 색을 조금 조정해 봐요.'],
[1,'available','/əˈveɪləbəl/','형용사','시간을 낼 수 있는','free · 이 문맥에서는 시간이 된다는 편한 말이에요.','unavailable · 시간을 낼 수 없는','미국 생활','I’m available …','I’m available after three.','저는 세 시 이후에 시간이 돼요.','Are you available tomorrow?','내일 시간 괜찮으세요?','Our instructor is available on Friday.','저희 강사님은 금요일에 시간이 되세요.'],
[1,'appointment','/əˈpɔɪntmənt/','명사','만나기로 정한 약속이나 예약','booking · 서비스나 자리를 예약하는 더 넓은 말이에요.',null,'미국 생활','I have an appointment …','I have an appointment at ten.','열 시에 예약이 있어요.','Can I make an appointment for Monday?','월요일로 예약할 수 있을까요?','I need to change my appointment.','예약을 변경해야 해요.'],
[1,'receipt','/rɪˈsiːt/','명사','영수증','proof of purchase · 구매 증빙이라는 더 넓은 표현이에요.',null,'미국 생활','Could I get a receipt for …?','I kept the receipt.','영수증을 보관했어요.','Could you email me the receipt?','영수증을 이메일로 보내 주시겠어요?','You’ll need your receipt for a return.','반품하려면 영수증이 필요해요.'],
[1,'refund','/ˈriːfʌnd/','명사','환불받는 돈','reimbursement · 대신 지출한 비용을 돌려받는 경우에 써요.',null,'미국 생활','I’d like a refund for …','The refund arrived today.','환불금이 오늘 들어왔어요.','Can I get a refund?','환불받을 수 있을까요?','Your refund will take a few days.','환불금이 들어오기까지 며칠 걸릴 거예요.'],
[1,'prefer','/prɪˈfɝː/','동사','더 좋아하다','favor · 특정 선택지를 더 지지하거나 선호한다는 뜻이에요.',null,'일상','I prefer … to …','I prefer tea to coffee.','커피보다 차를 더 좋아해요.','Would you prefer a morning class?','오전 수업이 더 좋으세요?','I prefer the simpler design.','저는 더 단순한 디자인이 좋아요.'],
[1,'comfortable','/ˈkʌmftərbəl/','형용사','몸이나 마음이 편안한','relaxed · 긴장이 풀렸다는 점을 강조해요.','uncomfortable · 불편한','몸과 움직임','I feel comfortable …','This chair is comfortable.','이 의자는 편안해요.','Are you comfortable in this position?','이 자세가 편안하세요?','I feel comfortable asking questions here.','여기서는 편하게 질문할 수 있어요.'],
[1,'balance','/ˈbæləns/','명사','몸이 한쪽으로 기울지 않는 균형','stability · 흔들리지 않는 안정성을 강조해요.',null,'몸과 움직임','I work on my balance by …','I lost my balance for a moment.','잠깐 균형을 잃었어요.','Can you keep your balance here?','이 자세에서 균형을 유지할 수 있나요?','This exercise helps with balance.','이 운동은 균형을 잡는 데 도움이 돼요.'],
[1,'support','/səˈpɔːrt/','동사','무게를 받쳐 주다','hold up · 받쳐 준다는 뜻을 풀어 쓴 표현이에요.',null,'몸과 움직임','I use … to support …','This shelf can support the books.','이 선반은 책의 무게를 받칠 수 있어요.','Could you support the other end?','반대쪽 끝을 받쳐 주시겠어요?','Use a cushion to support your head.','쿠션으로 머리를 받쳐 주세요.'],
[1,'layout','/ˈleɪaʊt/','명사','요소를 배치한 방식','arrangement · 사물의 배치를 가리키는 더 넓은 말이에요.',null,'디자인','I like the layout of …','The layout is easy to follow.','배치가 이해하기 쉬워요.','Can we change the layout?','배치를 바꿀 수 있을까요?','This layout leaves more space for text.','이 배치는 글을 넣을 공간이 더 넉넉해요.'],
[1,'account','/əˈkaʊnt/','명사','서비스를 이용하는 계정','profile · 계정에 연결된 소개나 설정 정보예요.',null,'디지털 생활','I need an account for …','I created an account yesterday.','어제 계정을 만들었어요.','How do I sign in to my account?','제 계정에 어떻게 로그인하나요?','You can change your account settings here.','여기에서 계정 설정을 바꿀 수 있어요.'],
[1,'confirm','/kənˈfɝːm/','동사','맞는지 확인해 주다','verify · 증거나 절차로 사실 여부를 확인하는 데 써요.',null,'미국 생활','Could you confirm …?','I called to confirm the time.','시간을 확인하려고 전화했어요.','Could you confirm my appointment?','제 예약을 확인해 주시겠어요?','Please confirm that this is the final design.','이것이 최종 디자인인지 확인해 주세요.'],
[2,'nuance','/ˈnuːɑːns/','명사','의미나 표현의 미묘한 차이','subtle difference · 뜻을 풀어 쓴 표현이에요.',null,'일상','I noticed a nuance in …','I missed the nuance of her reply.','그녀의 답변에 담긴 미묘한 뜻을 놓쳤어요.','Can you explain the nuance of this word?','이 단어의 미묘한 뜻 차이를 설명해 주시겠어요?','Her tone added a nuance of doubt.','그녀의 말투에서 약간의 의심이 느껴졌어요.'],
[2,'perspective','/pərˈspɛktɪv/','명사','어떤 일을 바라보는 관점','viewpoint · 어떤 문제를 바라보는 입장이에요.',null,'일상','From my perspective, …','I understand your perspective.','당신의 관점을 이해해요.','Could you share your perspective?','어떻게 생각하시는지 말씀해 주시겠어요?','My design background gives me a different perspective.','디자인을 공부한 경험 덕분에 다른 관점으로 보게 돼요.'],
[2,'subtle','/ˈsʌtəl/','형용사','쉽게 눈에 띄지 않는 미묘한','slight · 정도가 작다는 점에 초점을 둬요.','obvious · 쉽게 알아볼 수 있는','디자인','There is a subtle difference between …','There is a subtle difference.','미묘한 차이가 있어요.','Can you see the subtle change in color?','색의 미묘한 변화가 보이세요?','The pattern adds a subtle texture.','그 무늬가 은은한 질감을 더해 줘요.'],
[2,'consistent','/kənˈsɪstənt/','형용사','일관된','steady · 큰 변동 없이 유지된다는 점을 강조해요.','inconsistent · 일관되지 않은','일상','I want to be consistent with …','Her work is consistent in quality.','그녀의 작업은 품질이 일정해요.','Can we keep the colors consistent?','색을 일관되게 유지할 수 있을까요?','A consistent routine helps me practice.','규칙적인 일과가 연습에 도움이 돼요.'],
[2,'priority','/praɪˈɔːrəti/','명사','먼저 중요하게 챙겨야 할 일','main concern · 가장 신경 쓰는 일이라는 표현이에요.',null,'일상','My priority this week is …','Rest is my priority today.','오늘은 쉬는 것이 우선이에요.','What is your top priority?','가장 먼저 챙겨야 할 일은 무엇인가요?','Clear instructions are a priority in class.','수업에서는 명확한 설명이 우선이에요.'],
[2,'clarify','/ˈklærəfaɪ/','동사','뜻을 더 분명하게 설명하다','explain · 설명한다는 더 넓은 뜻이에요.',null,'일상','Could you clarify …?','That example clarified the idea.','그 예시 덕분에 개념이 더 분명해졌어요.','Could you clarify what you mean?','무슨 뜻인지 좀 더 설명해 주시겠어요?','The sketch helps clarify the layout.','스케치가 배치를 분명하게 설명하는 데 도움이 돼요.'],
[2,'alignment','/əˈlaɪnmənt/','명사','몸이나 사물이 바르게 놓인 상태','positioning · 위치를 잡는 방식으로, 바른 정렬만 뜻하지는 않아요.','misalignment · 정렬이 어긋난 상태','몸과 움직임','I’m working on the alignment of …','The wheels are out of alignment.','바퀴 정렬이 어긋나 있어요.','Could you check my alignment?','제 몸의 정렬을 확인해 주시겠어요?','Keep your head in alignment with your spine.','머리를 척추와 나란히 유지하세요.'],
[2,'tension','/ˈtɛnʃən/','명사','근육이 긴장하여 팽팽한 상태','tightness · 뻣뻣하거나 조이는 느낌을 강조해요.','relaxation · 긴장이 풀린 상태','몸과 움직임','I feel tension in my …','I feel tension in my shoulders.','어깨에 긴장이 느껴져요.','Do you notice any tension in your neck?','목에 긴장이 느껴지시나요?','Slow breathing can help release muscle tension.','천천히 숨 쉬면 근육의 긴장을 푸는 데 도움이 될 수 있어요.'],
[2,'contrast','/ˈkɑːntræst/','명사','서로 뚜렷하게 다른 모습','difference · 모든 종류의 차이를 가리키는 더 넓은 말이에요.','similarity · 서로 닮은 점','디자인','I like the contrast between …','The contrast between the two rooms is clear.','두 방의 차이가 뚜렷해요.','Could we add more contrast between the text and background?','글자와 배경의 대비를 더 줄 수 있을까요?','The dark frame creates a strong contrast with the white wall.','어두운 액자가 흰 벽과 뚜렷한 대비를 이뤄요.'],
[2,'revision','/rɪˈvɪʒən/','명사','내용을 고친 것 또는 고치는 일','edit · 글이나 파일의 개별 수정에도 자주 써요.',null,'디자인','I made a revision to …','This revision is easier to read.','이번 수정본은 읽기가 더 쉬워요.','Could you make one more revision?','한 번만 더 수정해 주시겠어요?','The latest revision has a simpler layout.','최근 수정본은 배치가 더 단순해요.'],
[2,'subscription','/səbˈskrɪpʃən/','명사','정기적으로 이용하는 구독','membership · 단체나 서비스의 회원 자격에 초점을 둬요.',null,'디지털 생활','I want to cancel my subscription to …','My subscription renews tomorrow.','제 구독이 내일 갱신돼요.','How do I cancel my subscription?','구독은 어떻게 취소하나요?','The subscription includes online classes.','구독에 온라인 수업이 포함돼요.'],
[2,'verify','/ˈvɛrəfaɪ/','동사','사실인지 확인하다','check · 확인하거나 살펴본다는 더 넓은 말이에요.',null,'디지털 생활','I need to verify …','I need to verify my email address.','이메일 주소를 인증해야 해요.','Could you verify this information?','이 정보가 맞는지 확인해 주시겠어요?','Please verify the measurements before printing.','인쇄하기 전에 치수가 맞는지 확인해 주세요.']
];
export const CONTENT_VERSION = 'sample-2026-09-v1';
export const editions = [
  { title:'생활의 기초', subtitle:'부탁하고, 대답하고, 일상을 시작하는 말.', goal:1000, color:'#32735a', label:'기본', newCount:1000 },
  { title:'대화의 확장', subtitle:'경험을 나누고, 이유와 생각을 전하는 말.', goal:4000, color:'#3e6799', label:'중급', newCount:3000 },
  { title:'이해의 깊이', subtitle:'관점을 넓히고, 미묘한 차이까지 표현하는 말.', goal:10000, color:'#7b5684', label:'확장', newCount:6000 }
];
export const items = rows.map(([level,text,ipa,pos,meaning,syn,ant,category,prompt,...examples]) => ({
  id:`word:${text}:01`, kind:'word', version:CONTENT_VERSION, text, meaning, level, category,
  pronunciation:{locale:'en-US',ipa,audioAsset:null,source:'기기의 음성 합성 기능'},
  word:{pos,forms:[],relations:{syn,ant}},
  examples:[0,2,4].map(i=>({en:examples[i],ko:examples[i+1],context:category})),
  prompt, usage:category, sources:[],
  review:{status:'draft',note:'직접 작성한 학습용 샘플 · 언어 검수 전',cefr:'미확인',selection:'인계 리서치의 생활 활용 기준에 따른 편집 선정',textRights:'자체 작성',audioRights:'음성 파일 미포함'}
}));
